### ISSUE TITLE
Kompetensförsörjningsplan DV

### ISSUE THREAD

**Issue by morganericsson** [morganericsson/msengcs#15]

**Comment by jesan-dv-lnu** [comment]
##Kompetensförsörjning och kontinuerligt kompetensutvveckling.
Fakulteten och institutionerna arbetar aktivt med
kompetensförsörjning. Kompetensförsörjning avser säkerställa att rätt
kompetens finns för att nå de berörda verksamheternas mål både på kort
och på lång sikt. Universitetet har utarbetat ett
universitetsövergripande instrument, kompetensförsörjningsplanen,
vilken syftar till att ge en översikt av befintlig kompetens och
tydliggöra kommande kompetensbehov. Befintligt och kommande behov
beskriver ett möjligt kompetensgap som används för att strategiskt
planera dels kompetensutvecklingsbehov av befintlig personal dels
rekryteringar. Planerna används även för att identifiera områden där
viss kompetens inte längre behövs och därmed kan avvecklas. Arbetet
med kompetensförsörjning har sin grund i universitetets styrdokument,
främst Linnéuniversitetets strategi, men även i beslutade policys,
planer och program. Även omvärlden påverkar, t ex demografi, politiska
beslut och konjunkturen på arbetsmarknaden. Institutionens
personalkonsult deltar som resurs i arbetet processen.

Kompetensförsörjningsplanerna arbetas fram på institutionsnivå och
kopplas därför direkt till behov inom grundutbildning,
forskarutbildning och forskning. Utveckling av utbildningsprogram och
kurser skapar ett kontinuerligt
kompetensutvecklingsbehov. Kompetensutvecklingsarbetet leds av
prefekten på aktuell institution. I samband med årliga
medarbetarsamtal och uppföljningssamtal planeras
kompetensutvecklingsaktiviteter i samverkan med undervisande
personal. Kompetensutvecklingstiden planeras inom ramen för
årsarbetstiden. Vid institutionen för datavetenskap avsätts 20% av
årsarbetstiden för planerad kompetensutveckling. Genom att
aktiviteterna planeras i samverkan och dessutom följs upp
kontinuerligt säkerställs eventuellt kompetensbehov inom
utbildningen. Kompetensutvecklingstiden kan överstiga 20% för vissa
medarbetare under kortare tid om man i planen har identifierat ett
akut behov som snabbt måste täckas. Kompetensutvecklings sker inom
flera områden, exempelvis högskolepedagogik och språk, men merparten
av aktiviteterna sker inom det egna ämnesområdet. För forskande
lektorer kan forskning utgöra en del av kompetensutvecklingsarbetet.

I vissa fall krävs att personal rekryteras för att hantera större förändringar inom
utbildningen eller för att täcka upp eventuella vakanser som
uppstår. Kompetensförsörjningsplanen är då ett instrument som används
för att beskriva rekryteringsprofiler. Vid rekryteringar beaktas både
grundutbildningens behov såväl som forskningens.

**Comment by jesan-dv-lnu** [comment]
#15 och #18
