### ISSUE TITLE
Beskrivning av forskning inom DV

### ISSUE THREAD

**Issue by morganericsson** [morganericsson/msengcs#22]

**Comment by jesan-dv-lnu** [comment]
Forskning inom datavetenskap

Forskningen inom datavetenskap riktar in sig mot teknik för att bygga smartare mjukvarusystem. Aktiviteterna bedrivs i huvudsak inom fyra forskningsområden med flera beröringspunkter:

- CPS – Cyber-fysikaliska system,
- ISOVIS – Informations och mjukvaruvisualisering,
- AdaptWise – Självanpassande mjukvarusystem och
- Software Technology Labs.

Forskningsgruppen för Cyber-fysikaliska Systems (CPS) studerar samverkan och återkoppling mellan de inbyggda mjukvarukomponenterna (cyber) och fysiska komponenterna, exempelvis, mekaniska komponenter, energisystem, mänskliga aktiviteter och omgivande miljö vilka utgör det sammanhållna systemet CPS-design tar hänsyn till flera faktorer som real-tids aspekter, energiförbrukning, tillförlitlighet, tillgänglighet och säkerhet. För att hantera denna komplexa verklighet krävs samverkan av experter från olika discipliner. Några av de konkreta utmaningarna finns inom modellering för analys, analyser, simuleringar, transformationstekniker för modell baserad utveckling, verifiering och realtids-analyser.

Gruppen fokuserar på flera aspekter, (i) modellbaserad design, syntes och verifikation av CPS, (ii) CPS-tillförlitlighet, säkerhet och integritet, (iii) storskalig dataanalys för CPS, (iv) hierarkisk modellering och optimering för CPS, samt (v) applikationer av CPS i smarta energisystem och transportsystem. Det huvudsakliga målet för forskningen, smartare system, studeras interaktionen mellan mjukvarusystemen, som tillhandahåller "smartare" och de fysiska enheter som utgör "systemen".

Informations- och mjukvaruvisualiseringsforskningen inom ISOVIS fokuserar på explorativ analys och visualisering av stora och komplexa informationsmängder, exempelvis från biovetenskap, humaniora eller mjukvaruutveckling. Vår vision är att attackera utmaningar kopplade till stora datamängder med en kombination av individ-centrerad dataanalys och interaktiv visualisering för förbättrat beslutsstöd.

En interaktiv visualisering och visuell analys ger effektivare och mer tillförlitliga analyser av de stora och komplexa datamängder som samlas in från smarta system. Som ett resultat kan vi skapa en bättre förståelse för och följaktligen också skapa bättre förutsättningar för att utveckla system, exempelvis öka möjligheterna att förutse systemens prestanda och konstrueras för att förbättra möjligheterna att förutsäga och kontrollera prestanda och beteende.

Forskargruppen AdaptWise studerar metoder och tekniker för självanpassande mjukvarusystem. Gruppen fokuserar på att skapa försäkringar för att systemen uppfyller de egenskaper som efterfrågas. Självanpassning är en princip för att hantera osäkerheter i driftsatta mjukvarusystem, exempelvis dynamisk resurstillgång och förändringar av kraven Att lägga till självtillpassningsfunktioner till programvarusystem gör det möjligt för dessa system att agera autonomt med en dynamik som är omöjlig att bestämma vid tidpunkten då systemen designas och implementeras. Därför kan dessa system ta över enformiga uppgifter som vanligtvis utförs av operatörer med kortare svarstider och med högre kvalitet, vilket ger smartare system.

Software Technology Labs studerar teknologier för dataintensiva mjukvarusystem. Maskininlärning och artificiell intelligens använder (stora) datamängder för att automatisera uppgifter som resonemang, planering, beslutsfattande och prediktion. Skalbara teknologier möjliggör en hantering av stora datavolymer, exempelvis i stora real-tids dataströmmar. Gruppen studerar även möjligheten att se IT-system som informationskällor. Idén är att på detta vis skapa möjligheter för kontinuerlig analys och därmed förbättra kvalitetsarbetet. 

Teknologi för dataintensiva mjukvarusystem möjliggör att omvandling av data till information och information till kunskap vilket bidrar till en enklare implementation av smartare system och vissa fal även en mer eller mindre helautomatisk generering av komponenter för dessa system.
