### ISSUE TITLE
Ledning och styrning av utbildningen inom DV

### ISSUE THREAD

**Issue by morganericsson** [morganericsson/msengcs#38]

**Comment by jesan-dv-lnu** [comment]
#Ledning och styrning vid Institutionen

Institutionens utbildningar hanteras av ett utbilildningsråd med ansvar för
planering, genomförande, samt kvalitetssäkring. Kvalitetssäkringsarbetet sker genom kontinuerliga
uppföljningar och förbättringsinsatser enligt universitetets fastställda regler.

## Organisation
Utbildningsrådet leds av en studierektor som fungerar
som är sammankallande och rapporterar direkt till fakultetens
utbildningsansvarig samt prefekt. Utbildningsrådet består, förutom studierektorn, av studeranderepresentanter, programansvariga,
ämnesansvariga samt administrativt stöd. Rådet träffas regelbundet minst fem gånger per år, en gång per läsperiod samt vid ett
planeringsmöte inför kommande kalenderår.

## Ansvar

Rådet ansvarar för utbildningens planering, genomförande samt
för de delar av kvalitetssäkringsarbetet som faller på institutionen.

Inför varje läsår diskuteras utbildningsplaner och
årsplaner för utbildningsprogrammen.  Varje program
följs upp inför ett nytt år för att skapa en bättre bild av
programmets aktualitet och interna kvalitet. Rådet ansvarar för uppföljningen
och att förändringsförslag samordnas mellan program och med berörda fakultetsfunktioner.

Kursvärderingar är ett viktigt instument för utbildningsrådet. På
varje möte under läsperioderna väljs ett par kursvärderingar ut för
närmare granskning och diskussion. Rådet kan komma med
rekommendationer kring kursplanens och literaturlistans utformning och
innehåll. En rekommendation initierar en revidering av kursplanen som
kursansvarig ansvaraför. Mindre förändringar bereds på
institutionsnivå och beslutas av prefekt. Större förändringar och ny
kurser förbereds av institutionen men hanteras i övrigt av fakultetens
funktioner.  Rekommendationer följs upp på efterföljande
möten. Studierektorn ansvarar för kontakter rörande kurser i andra
ämnen.

Inför varje kalenderår planeras resurser på de olika
kurserna. Studierektor ansvarar tillsammans med det administrativa
stödet för att resursplaneringen färdigställs inför varje
kalenderår. Kursansvarig ansvarar sedan för att resurserna
detaljplaneras. Planeringen följs upp kontinuerligt en gång per
läsperiod, då kurser i föregående period har återrapporterats. Detta
medför att årsplaneringen blir mer flexibel och att resurser kan
flyttas mellan olika aktiviteter för att på så sätt skapa en bättre
dynamik och effekt.

Studierektor ansvarar för att kursansvarig och lärarpersonal genomför
kurserna enligt universitetets uppställda regler.
