### ISSUE TITLE
Jämställdhetsperspektiv DV

### ISSUE THREAD

**Issue by morganericsson** [morganericsson/msengcs#40]

**Comment by jesan-dv-lnu** [comment]
##Jämställdhetsperspektiv

Linneuniversitetet arbetade under våren 2017 fram en plan för
jämstäldhetsintegrering vid lärosätet. Planen är en följd av det
nationella uppdrav som beslutats av regeringen där lärosäten uppmanats
att beskriva hur verksamheten skall jämstäldhetsintegreras. Planen för
jämställdhetsintegrationsarbetet går utvecklar universitetes arbete
för lika villkor. Fakulteterna och institutionerna håller för
närvarande på att analysera effekterna av planen på
verksamheten. Planen har ett klart medarbetarperspektiv vilket gör att
det i planen fokuseras mer på frågor som rekrytering och
karriärmöjligheter och mindre på aspekter som berör studenter och
utbildning så som program och kurs.

I planen för lika villkor uttrycks mer specifika indikatorer som kan
användas för att styra verksamheten. Fokus på aktiviteter med direkt
konsekvens för utbildnings program och kurser läggs på
fortbildningskurser.

Om vi väljer en utbildning och beskriver jämstäldhetsarbetet vid
fakulteten för teknik i allmänhet och institutionen för datavetenskap
specifikt kan vi i bättre detalj beskriva de praktiska konsekvenserna
av dessa båda planer. Utbildningens organisation och genomförande är
avgörande för graden av måluppfyllelse. DV har idag en kraftig
snedfördelning om man ser till kön, både avseende undervisande
personal och studenter. Detta är på intet sätt specifikt för lärosätet
utan samma tendenser ses på flertalet lärosäten som erbjuder
ingenjörsutbildningar inom datateknik.

Vid faktulteten och institutionen arbetar vi aktivt på två nivåer för
att förändra situationen. Den första nivån handlar om rekrytering av
både medarbetare och studenter, den andra handlar om utbildningens organisation och genomförande.

Kompetensförsörjningsplanen pekar klart och tydligt på den sneda
könsrepresentationen vilket återspeglas i rekryteringsprocessen och
anställningsprofiler. Institutionen driver och deltar dessutom ett
flertal aktiviteter riktat mot olika grupper för att väcka ett
intresse för tekniska utbildningar, i synnerhet datateknik.

Inom våra utbildningsprogram och kurser arbetar vi aktivt med att
dessa skall erbjuda flera olika lärsituationer för att passa en större
grupp studenter. Vi arbetar mer och mer med projekt istället för
traditionell katederundervisning, även om det senare fortfarande
används. Tanken är att detta skall skapa ett lärande som handlar mer
om individens personliga utveckling i situationer som i så stor grad
som möjligt liknar de som individen kommer att befinna sig i sitt
yrkesliv. Inom ramen för jämstäldshetsintegrering och lika villkor
arbetas specifika moment fram som syftar till att utbiilda medarbetare
i hur man aktivt kan arbeta för mer jämställda kurser avseende
innehåll, material och kommunikation. Denna process är viktig men
långsiktig och har precis påbörjats. Därför kan vi inte se några
effekter av detta arbete i nuvarande utbildningsprogram eller kurser utan vi förväntar oss
avtryck i de nya kurser som vi tar fram inom ramen för en ny
civilingenjörsutbildning.
